name: Greetings

on: workflow_dispatch

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
     - name: greeting to world
       id: my-script
       run: |
         echo '======================================'
         printenv
         echo '======================================'
         
